name: Review Assign

on:
  pull_request:
    types: [opened, reopened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: hkusu/review-assign-action@v1.4.0
        with:
          assignees: ${{ github.actor }}
          reviewers: |
            ohdeng02
            rigyeonghong
            JoHyoju04
            LeeJuHwan
      - name: Show result
        if: always()
        run: echo '${{ steps.assign.outputs.result }}' # success or failure
